/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotelmanagementsystemproject;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime; 

/**
 *
 * @author raahi
 */
public class bookARoom extends javax.swing.JFrame {
    
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yy  HH:mm:ss");   
    
    roomBook room = new roomBook();
    
    //To get IndexNumber of ListElement
    int Index;
    int SelectedIndex;
    //stores roomName
    String roomName;
    // To Store data in List Object
    DefaultListModel<String> listModel;
    /**
     * Creates new form bookARoom
     */
    public bookARoom() {
        initComponents();
        listModel = new DefaultListModel(); //Initiallizing the list model
         for(int i=1 ; i<100;i++){
             listModel.addElement(room.roomNoArray[i]);
            roomBookInfo.setModel(listModel);
         }
            
         
//        for(int i=1 ; i<=100;i++){
//            
//                if(i<=10){
//                    roomName = "Room " + i + " (VIP) " ;
//                }
//                else{
//                    roomName = "Room " + i;
//                }
//            listModel.addElement(roomName);
//            roomBookInfo.setModel(listModel);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bookRoomBtn = new javax.swing.JButton();
        emptyRoomBtn = new javax.swing.JButton();
        customerDetails = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomBookInfo = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        bookRoomBtn.setText("Book Room");
        bookRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomBtnActionPerformed(evt);
            }
        });

        emptyRoomBtn.setText("Empty Room");
        emptyRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyRoomBtnActionPerformed(evt);
            }
        });

        customerDetails.setText("Enter Customer Name");
        customerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDetailsActionPerformed(evt);
            }
        });

        roomBookInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomBookInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(roomBookInfo);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emptyRoomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(bookRoomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(187, 187, 187)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerDetails)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(bookRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(emptyRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(358, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(customerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomBookInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomBookInfoMouseClicked
        // TODO add your handling code here:
        String roomName = roomBookInfo.getSelectedValue();
        
        for(int i=0 ; i<100 ; i++){
            if(roomName.equals(room.roomNoArray[i])){
                Index = i;
            }
        }
        Index = roomBookInfo.getSelectedIndex();
    }//GEN-LAST:event_roomBookInfoMouseClicked

    private void bookRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomBtnActionPerformed
        // TODO add your handling code here:
         String customerDetail = customerDetails.getText();
         room.roomNoArray[Index] =  customerDetails.getText();
         
         LocalDateTime dt = LocalDateTime.now();
         String myDate = dt.format(dtf);
         
      if(customerDetail.equals("")){
          JOptionPane.showMessageDialog(null,"Enter Name of Customer");
          
      }
      else if(Index == -1){
          JOptionPane.showMessageDialog(null,"Select a Room Number");
          
      }
      else{
          if(Index<10){
                listModel.setElementAt("Room " + (Index + 1) + (" VIP ROOM")+" (" + room.roomNoArray[Index]+ " ) (BOOKED) Time of Booking: "+ myDate , Index);
                System.out.println(room.roomNoArray[Index]);
                
            }
          else{
        listModel.setElementAt("Room " + (Index + 1) +" (" + room.roomNoArray[Index] + " ) (BOOKED) Time of Booking: " + myDate, Index);
          }
          }
    }//GEN-LAST:event_bookRoomBtnActionPerformed

    private void emptyRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyRoomBtnActionPerformed
        // TODO add your handling code here:
            if(Index<=10){
                    room.roomNoArray[Index] = "Room " + (Index + 1)+ " (VIP) ";
                    
                }
                else{
                     room.roomNoArray[Index] = "Room " + (Index + 1);
                }
           listModel.setElementAt(room.roomNoArray[Index], Index);
       
       
    }//GEN-LAST:event_emptyRoomBtnActionPerformed

    private void customerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerDetailsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainPage goBack = new MainPage();
        bookARoom visibility = new bookARoom();
        goBack.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookARoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookARoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookARoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookARoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookARoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookRoomBtn;
    private javax.swing.JTextField customerDetails;
    private javax.swing.JButton emptyRoomBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> roomBookInfo;
    // End of variables declaration//GEN-END:variables
}
