/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotelmanagementsystemproject;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author raahi
 */
public class roomBookingg extends javax.swing.JFrame {
    MainPage mainPage = new MainPage();
    roomBooking roomBooking1 = new roomBooking();
     int Index = -1;
     DefaultListModel<String> listModel;
    /**
     * Creates new form roomBookingg
     */
    public roomBookingg() {
        initComponents();
         listModel = new DefaultListModel<>();
        
        for(int i =1 ; i<=100 ; i++){
            if(i<=10){
                listModel.addElement("Room " + i + (" VIP ROOM"));
                continue;
            }
            listModel.addElement("Room " + i);
            roomBookingInfo.setModel(listModel);
            
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerDetails = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomBookingInfo = new javax.swing.JList<>();
        bookRoomBtn1 = new javax.swing.JButton();
        emptyRoomBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerDetails.setText("jTextField1");
        customerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerDetailsActionPerformed(evt);
            }
        });

        roomBookingInfo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(roomBookingInfo);

        bookRoomBtn1.setText("jButton1");
        bookRoomBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomBtn1ActionPerformed(evt);
            }
        });

        emptyRoomBtn.setText("jButton1");
        emptyRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyRoomBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookRoomBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(emptyRoomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(customerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(customerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bookRoomBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(emptyRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emptyRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyRoomBtnActionPerformed
        // TODO add your handling code here:
        listModel.setElementAt("Room " + (Index + 1), Index);
    }//GEN-LAST:event_emptyRoomBtnActionPerformed

    private void bookRoomBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomBtn1ActionPerformed
        // TODO add your handling code here:
        String customerDetail = customerDetails.getText();
      
      if(customerDetail.equals("")){
          JOptionPane.showMessageDialog(null,"Enter Name of Customer");
          
      }
      else if(Index == -1){
          JOptionPane.showMessageDialog(null,"Select a Room Number");
          
      }
      else{
          if(Index<10){
                listModel.setElementAt("Room " + (Index + 1) + (" VIP ROOM")+" (" + customerDetail+ " ) (BOOKED) Time of Booking: " , Index);
                
            }
          else{
        listModel.setElementAt("Room " + (Index + 1) +" (" + customerDetail+ " ) (BOOKED) Time of Booking: " , Index);
          }
          }
    }//GEN-LAST:event_bookRoomBtn1ActionPerformed

    private void customerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerDetailsActionPerformed
        // TODO add your handling code here:
        customerDetails.setText("");
    }//GEN-LAST:event_customerDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roomBookingg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roomBookingg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roomBookingg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roomBookingg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roomBookingg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookRoomBtn1;
    private javax.swing.JTextField customerDetails;
    private javax.swing.JButton emptyRoomBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> roomBookingInfo;
    // End of variables declaration//GEN-END:variables
}
